name: common_github_search
description: Shared Code between AngularDart and Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  bloc: ^2.0.0
  rxdart: ^0.22.6
  http: ^0.12.0+2
  equatable: ^1.0.1