name: flutter_architectures
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  intl: ^0.15.8

  rflutter_alert: ^1.0.3
  cached_network_image: ^1.1.2+1
  connectivity: ^0.4.5+2
  cupertino_icons: ^0.1.2

  path_provider: ^1.4.0

  provider: ^3.1.0+1

  json_annotation: ^3.0.0

  built_value: ^6.7.1
  built_collection: ^4.2.2

  hive: ^1.1.1
  hive_flutter: ^0.2.1

  moor_flutter: ^2.0.0
  moor: ^2.0.1+1

  chopper: ^3.0.1

  retrofit: ^1.0.1

  dio_flutter_transformer: ^3.0.2

  pretty_dio_logger: ^1.0.7

  dio_http2_adapter: ^1.0.0

  intro_views_flutter: ^2.8.0
  flutter_svg: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1

  intl_translation: ^0.17.7

  json_serializable: ^3.2.0

  built_value_generator: ^6.7.1

  hive_generator: ^0.5.2

  moor_generator: ^2.0.1

  chopper_generator: ^3.0.0

  retrofit_generator: ^1.0.1+2





flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pngs/
    - assets/svgs/
    - lang/
